<a href="https://colab.research.google.com/github/gustavoshelby0/googlecolab-py/blob/main/3-Hashtag_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import pandas as pd
import numpy as np

In [42]:
# df = pd.read_csv('')

In [43]:
dados = {
    'Nome':['Ana','Bruno','Carlos','Daniela','Eduardo'],
    'idade':['25','30','35','40','46'],
    'Area':['Adm','Financeiro','Adm','Sales','Financeiro'],
    'Salario':['3000','5000','7000','9000','11000']
}


df = pd.DataFrame(dados)

display(df)

      Nome idade        Area Salario
0      Ana    25         Adm    3000
1    Bruno    30  Financeiro    5000
2   Carlos    35         Adm    7000
3  Daniela    40       Sales    9000
4  Eduardo    46  Financeiro   11000

In [44]:
#describe

df.describe()

       Nome idade Area Salario
count     5     5    5       5
unique    5     5    3       5
top     Ana    25  Adm    3000
freq      1     1    2       1

In [45]:
# aplicar aumento no salario dos funcionarios

df.info()

df['Salario'] = df['Salario'].astype(float)


df['Salario Ajustado'] = df['Salario'].apply(lambda x: x * 1.1)
display(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Nome     5 non-null      object
 1   idade    5 non-null      object
 2   Area     5 non-null      object
 3   Salario  5 non-null      object
dtypes: object(4)
memory usage: 292.0+ bytes

      Nome idade        Area  Salario  Salario Ajustado
0      Ana    25         Adm   3000.0            3300.0
1    Bruno    30  Financeiro   5000.0            5500.0
2   Carlos    35         Adm   7000.0            7700.0
3  Daniela    40       Sales   9000.0            9900.0
4  Eduardo    46  Financeiro  11000.0           12100.0

In [46]:
# quero a media de salario por area


df_media_area = df.groupby('Area').mean(numeric_only=True)
display(df_media_area)

            Salario  Salario Ajustado
Area
Adm          5000.0            5500.0
Financeiro   8000.0            8800.0
Sales        9000.0            9900.0

In [52]:
# tire as linhas com valores NaN

mean_salarial = df['Salario'].mean()
df['Salario'] = df['Salario'].fillna(mean_salarial)
df['Salario Ajustado'] = df['Salario Ajustado'].fillna(df['Salario Ajustado'].mean)
display(df)

      Nome idade        Area  Salario  Salario Ajustado
0      Ana    25         Adm   3000.0            3300.0
1    Bruno    30  Financeiro   5000.0            5500.0
2   Carlos    35         Adm   7000.0            7700.0
3  Daniela    40       Sales   9000.0            9900.0
4  Eduardo    46  Financeiro  11000.0           12100.0

In [ ]:
# merge um procv or join do SQL